sudo: true
dist: trusty
language: node_js
node_js:
  - "9"

jobs:
  include:
    - stage: test
      script: npm test
    - stage: build-image
      script: npm run build-ts
      script: npm run build-image
      script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script: npm run push-image