sudo: true
dist: trusty
language: node_js
node_js:
  - "9"

jobs:
  include:
    #- stage: test
    #  script: npm test
    #- stage: build-image
    #  script: 
    #   - npm run build-ts
    #   - npm run build-image
    #   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    #   - npm run push-image
    - stage: test-integration
      script: 
       - npm run test-image
       - cd test/integration
       - docker ps
       - sh ./test.sh
       - npm run stop-container
       - npm run remove-container