version: '2.1'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 3031:3031

  documents:
    depends_on:
      - mongodb
    image: tbushinger/remix-vinyl
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 27017:27017